# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-03 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160521_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('students_list', 'List all students'), ('student_show', 'Show the information of student.'), ('student_create', 'Create a new student.'), ('student_edit', 'Edit the information of students.'), ('student_del', 'Delete students'), ('org_managers_list', 'List all managers of an organization.'), ('org_managers_create', 'Create a new manager.'), ('org_managers_del', 'Remove a manager from an organization.'), ('members_list', 'List the members in an organization.'), ('member_show', 'Show the information of member.'), ('member_create', 'Create a new member in organization.'), ('member_del', 'Remove a member from an organization.'), ('website_admin', '\u5b66\u5b50\u5929\u5730\u7f51\u7ad9\u7ba1\u7406\u5458'), ('student_manager', '\u5b66\u751f\u5e10\u53f7\u7ba1\u7406\u5458'), ('free_time_count', '\u7a7a\u95f2\u65f6\u95f4\u67e5\u770b\u7cfb\u7edf'))},
        ),
    ]
