# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-04 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20160427_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('banned', models.BooleanField(default=False)),
                ('create_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('reply', models.TextField(blank=True, max_length=200)),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.Article')),
                ('editor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
